### ISSUE TITLE
Hubitat Package Manager Matching

### ISSUE THREAD

**Issue by virusuf86** [sburke781/ecowitt#25]
I initially installed the code manually to my Hubitat and set up everything. I recently discovered Hubitat Package Manager, but it seems its unable to match the drivers. I tried installing the drivers via HPM, switch the device type to the newly installed Ecowitt WiFi Gateway driver, but sensor device type is grayed out and I cant manually switch it to the new Ecowitt RF sensor driver.

Im not sure if there is a line of code in the manual installation of the Ecowitt drivers where HPM cant pick it up or if its HPM's fault.

**Comment by sburke781** [comment]
If you have existing automations or use the devices you created under the manually installed drivers, then the short answer is I suspect you will need to follow the steps I wrote for those transitioning from Mirco's version of these drivers to mine, but let me take a little more time to think it through some more.

https://community.hubitat.com/t/re-release-ecowitt-and-wittboy-weather-stations-and-sensors-local/78492/9?u=sburke781

If you do not currently use your existing devices in any automations, dashboards, etc, then I would remove the drivers in HPM, remove the existing EcoWitt devices, remove the manually installed drivers, then install the drivers from HPM and create the gateway device again, syncing the sensors.

**Comment by virusuf86** [comment]
I did the manual migration. One tip is that I added "_OLD" to all my Ecowitt device labels and the manually loaded drivers. It made it much easier to swap devices on my dashboards and pistons.

**Comment by sburke781** [comment]
Thanks for the tip @virusuf86.  Does this mean you have successfully setup your Gateway and sensors using the drivers installed via HPM?  And so you are happy to see this issue closed?

**Comment by virusuf86** [comment]
Yup. Sure.
