### ISSUE TITLE
Add support for Soil Moisture Sensor

### ISSUE THREAD

**Issue by sethhere04** [sburke781/ecowitt#9]
Does this support the Soil Moisture Sensor? If not, can this be added?

**Comment by sburke781** [comment]
Sorry I missed this @sethhere04, I don't log on here as much as I should.  Feel free to post questions on the [EcoWitt Hubitat Community thread](https://community.hubitat.com/t/re-release-ecowitt-gw1000-wi-fi-gateway/78492?u=sburke781) (if you are a member).

Yes, the drivers do support the Soil Moisture Sensors.  I have some myself, but have not actively used them in my automations yet.  You will see "humidity" readings in child devices of the gateway.

![image](https://user-images.githubusercontent.com/4384353/174287293-d9f54f51-9831-40cc-80b3-0835c94a62c0.png)

![image](https://user-images.githubusercontent.com/4384353/174287739-28019c15-5585-41d0-9385-3ff7f185a3d4.png)

**Comment by sburke781** [comment]
Might close this issue @sethhere04.  Like I mentioned earlier, the Soil Moisture sensors are supported.  If you have any issues setting one up or any more questions, just raise another issue here or post a question on the Hubitat Community.  Happy to help where I can.
